gamepad_span: 200.0
pwm_freq_hz: 50.0
neutral_us: 1500.0
max_pwm_us: 1900.0
min_pwm_us: 1100.0
update_rate_hz: 10.0

enable_pitch_control: true


twist_vel_xy: 0.4
twist_vel_z: 0.4
twist_yaw_rate: 0.6
twist_pitch_rate: 0.6

distance_topic: /stereo/min_distance
min_distance_before_safety: 0.0


usb_joy_button_a: 0
usb_joy_button_b: 1
usb_joy_button_x: 2
usb_joy_button_y: 3
usb_joy_button_power: 8
usb_joy_button_setting: 7
usb_joy_button_option: 6

usb_joy_left_stick_up_down: 1
usb_joy_left_stick_left_right: 0
usb_joy_right_stick_up_down: 4
usb_joy_right_stick_left_right: 3
usb_joy_left_trigger: 2
usb_joy_right_trigger: 5

bluetooth_joy_button_a: 0
bluetooth_joy_button_b: 1
bluetooth_joy_button_x: 3
bluetooth_joy_button_y: 4
bluetooth_joy_button_power: 12
bluetooth_joy_button_setting: 11
bluetooth_joy_button_option: 10

bluetooth_joy_left_stick_up_down: 1
bluetooth_joy_left_stick_left_right: 0
bluetooth_joy_right_stick_up_down: 3
bluetooth_joy_right_stick_left_right: 2
bluetooth_joy_left_trigger: 5
bluetooth_joy_right_trigger: 4
